# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MXPDQywA-9daQOu9aCs_Ju_IPWP39YbY
"""

from getpass import getpass
from socket import *
from base64 import *
import ssl

YOUR_EMAIL = input("Gönderici maili giriniz: ")
YOUR_PASSWORD = getpass("Mail şifresini giriniz : ")
YOUR_DESTINATION_EMAIL = input("Alıcı mailini giriniz: ")
YOUR_SUBJECT_EMAIL = input("Konuyu giriniz : ")
YOUR_BODY_EMAIL = input("Mesajı giriniz : ")

msg = '{}. \r\nÖdev Başarıyla Tamamlandı'.format(YOUR_BODY_EMAIL)
endmsg = '\r\n.\r\n'

mailServer = 'smtp.gmail.com'
mailPort = 587

clientSocket = socket(AF_INET, SOCK_STREAM)
clientSocket.connect((mailServer, mailPort))

recv = clientSocket.recv(1024)
print (recv)
if recv[:3] != '220':
	print ('220 reply not received from server.')

heloCommand = 'EHLO beyza  \r\n'.encode()
clientSocket.send(heloCommand)
recv1 = clientSocket.recv(1024)
print (recv1)
if recv1[:3] != '250':
	print ('250 reply not received from server.')

strtlscmd = "STARTTLS\r\n".encode()
clientSocket.send(strtlscmd)
recv2 = clientSocket.recv(1024)

sslClientSocket = ssl.wrap_socket(clientSocket)

EMAIL_ADDRESS = b64encode(YOUR_EMAIL.encode())
EMAIL_PASSWORD = b64encode(YOUR_PASSWORD.encode())

authorizationcmd = "AUTH LOGIN\r\n"

sslClientSocket.send(authorizationcmd.encode())
recv2 = sslClientSocket.recv(1024)
print(recv2)

sslClientSocket.send(EMAIL_ADDRESS + "\r\n".encode())
recv3 = sslClientSocket.recv(1024)
print(recv3)

sslClientSocket.send(EMAIL_PASSWORD + "\r\n".encode())
recv4 = sslClientSocket.recv(1024)
print(recv4)

mailfrom = "MAIL FROM: <{}>\r\n".format(YOUR_EMAIL)
sslClientSocket.send(mailfrom.encode())
recv5 = sslClientSocket.recv(1024)
print(recv5)

rcptto = "RCPT TO: <{}>\r\n".format(YOUR_DESTINATION_EMAIL)
sslClientSocket.send(rcptto.encode())
recv6 = sslClientSocket.recv(1024)

data = 'DATA\r\n'
sslClientSocket.send(data.encode())
recv7 = sslClientSocket.recv(1024)
print(recv7)


sslClientSocket.send("Subject: {}\n\n{}".format(YOUR_SUBJECT_EMAIL, msg).encode())

sslClientSocket.send(endmsg.encode())
recv8 = sslClientSocket.recv(1024)
print(recv8)

quitcommand = 'QUIT\r\n'
sslClientSocket.send(quitcommand.encode())
recv9 = sslClientSocket.recv(1024)
print(recv9)

sslClientSocket.close()